In [3]:
import pandas as pd

In [11]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Salary": [50000, 60000, 70000]
}

df = pd.DataFrame(data)
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000

In [12]:
print(df[['Name','Salary']])

      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   70000

In [14]:
filtered_df = df[df['Age'] > 28]
print(filtered_df)

      Name  Age  Salary
1      Bob   30   60000
2  Charlie   35   70000

In [7]:
df['Bonus'] = df['Salary'] * 0.1
print(df)

      Name  Age  Salary   Bonus
0    Alice   25   50000  5000.0
1      Bob   30   60000  6000.0
2  Charlie   35   70000  7000.0

In [9]:
data = {
    "Student": ["A", "B", "C", "D"],
    "Marks": [85, None, 78, None]
}

df = pd.DataFrame(data)

df['Marks'] = df['Marks'].fillna(df['Marks'].mean())
print(df)

  Student  Marks
0       A   85.0
1       B   81.5
2       C   78.0
3       D   81.5

#### groupby()

In [ ]:

import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Salary": [60000, 50000, 70000, 52000, 65000]
}

df = pd.DataFrame(data)

df1 = df.groupby('Department')['Salary'].mean()
print(df1)

Department
Finance    65000.0
HR         51000.0
IT         65000.0
Name: Salary, dtype: float64

In [4]:
df = pd.DataFrame({"Number": [1, 2, 3, 4, 5]})

print(df)
print(df.columns)

   Number
0       1
1       2
2       3
3       4
4       5
Index(['Number'], dtype='object')

#### apply()

In [5]:
df["Type"] = df['Number'].apply(
    lambda x: "Even" if x % 2 == 0 else "Odd"
)

print(df.to_string(index=False))

 Number Type
      1  Odd
      2 Even
      3  Odd
      4 Even
      5  Odd

#### map

In [6]:
df["Type"] = df['Number'].map(
    lambda x: "Even" if x % 2 == 0 else "Odd"
)

print(df.to_string(index=False))

 Number Type
      1  Odd
      2 Even
      3  Odd
      4 Even
      5  Odd

In [8]:
import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "HR", "Finance"],
    "Salary": [60000, 50000, 70000, 52000, 65000]
}

df = pd.DataFrame(data)

#### agg()

In [9]:
df.groupby("Department").agg(
    avg_salary=("Salary", "mean"),
    max_salary=("Salary", "max")
).reset_index()

  Department  avg_salary  max_salary
0    Finance     65000.0       65000
1         HR     51000.0       52000
2         IT     65000.0       70000

#### vectorization

In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame({"Number": [1, 2, 3, 4, 5]})

df['Type'] = np.where(df['Number'] % 2 == 0, 'Even', 'Odd')

print(df)

   Number  Type
0       1   Odd
1       2  Even
2       3   Odd
3       4  Even
4       5   Odd

#### np.select

In [15]:
df = pd.DataFrame({"Age": [12, 25, 45, 70]})

conditions = [
    df["Age"] < 18,
    df["Age"].between(18, 60),
    df["Age"] > 60
]

choices = ["Minor", "Adult", "Senior"]

df["Category"] = np.select(conditions, choices, default="Unknown")
print(df)

   Age Category
0   12    Minor
1   25    Adult
2   45    Adult
3   70   Senior

#### Pure Pandas Vectorized Way (No NumPy)

In [13]:
df["Type"] = df["Number"].mod(2).map({0: 'Even', 1:'Odd'})
print(df)

   Number  Type
0       1   Odd
1       2  Even
2       3   Odd
3       4  Even
4       5   Odd

#### merge two df and joins

In [16]:
df1 = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["A", "B", "C"]
})

df2 = pd.DataFrame({
    "EmpID": [1, 2, 4],
    "Salary": [50000, 60000, 70000]
})

merge_Df = pd.merge(df1, df2, on='EmpID', how='inner')

print(merge_Df)

   EmpID Name  Salary
0      1    A   50000
1      2    B   60000

#### find duplicate emails

In [25]:
df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "Email": ["a@gmail.com", "b@gmail.com", "a@gmail.com", "d@gmail.com"]
})

print(df)

  Name        Email
0    A  a@gmail.com
1    B  b@gmail.com
2    C  a@gmail.com
3    D  d@gmail.com

In [26]:
duplicates = df[df.duplicated(subset=['Email'], keep=False)]
print(duplicates)

  Name        Email
0    A  a@gmail.com
2    C  a@gmail.com

In [35]:
df.drop_duplicates(subset=["Email"])
df

  Name        Email
0    A  a@gmail.com
1    B  b@gmail.com
3    D  d@gmail.com

In [1]:
a = [1, 2, 3]
b = a
b.append(4)
print(a)

[1, 2, 3, 4]

In [17]:
def func(x=[]):
    x.append(1)
    return x

print(func())
print(func())
print(func())

[1]
[1, 1]
[1, 1, 1]

In [20]:
def func(x=None):
    if x is None:
        x = []
    x.append(1)
    return x
print(func())
print(func())

[1]
[1]

In [3]:
import copy

a = [[1, 2], [3, 4]]
b = copy.copy(a)
b[0].append(99)

print(a)

[[1, 2, 99], [3, 4]]

In [4]:
x = 10

def test():
    x = 20

test()
print(x)

10

In [6]:
nums = [1, 2, 3, 4]
result = [n*n for n in nums if n % 2 == 0]
print(result)

[4, 16]

In [ ]:
a = [1, 2, 3]
b = [1, 2, 3]

print(a == b)
print(a is b)

True
True

In [12]:
try:
    x = int("10a")
except ValueError:
    print("Value Error")
finally:
    print("Done")

Value Error
Done

In [15]:
def f():
    return
    print("Hello")

print(f())

None

In [16]:
nums = (x*x for x in range(3))

print(list(nums))
print(list(nums))

[0, 1, 4]
[]

#### Kadane's Algorithm

In [ ]:
"""def sub_array(num_list):
    length = len(num_list)
    sum_list = []
    for i in range(length):
        for j in range(i+1, length+1):
            print(num_list[i:j])
            sum_list.append(sum(num_list[i:j]))
    return max(sum_list)

sub_array([1,2,3])"""

# Kadane's Algorithm

def max_subarray(nums):
    max_sum = nums[0]
    current_sum = nums[0]

    for i in range(1, len(nums)):
        current_sum = max(nums[i], current_sum + nums[i])
        max_sum = max(max_sum, current_sum)

    return max_sum

print(max_subarray([-2,1,-3,4,-1,2,1,-5,4]))

6

#### Two pointer strategy

In [28]:
def pair_with_sum(arr, target):
    left = 0
    right = len(arr)-1

    while left < right:
        current_sum = arr[left] + arr[right]

        if current_sum == target:
            return True, (arr[left], arr[right])
        elif current_sum < target:
            left += 1
        else:
            right -= 1
    
    return False, None

arr = [1,2,3,4,5,6,7]
target = 5

found, pair = pair_with_sum(arr, target)

if found:
    print("Pair found:", pair)
else:
    print("No pair found")

Pair found: (1, 4)

#### find the **first repeating element**

In [ ]:
# (index-based first repeat)

arr = [10, 5, 3, 4, 3, 5, 6]

found = False

for i in range(len(arr)):
    for j in range(i + 1, len(arr)):
        if arr[i] == arr[j]:
            print("First repeating element is:", arr[i])
            found = True
            break
    if found:
        break

First repeating element is: 5

In [2]:
seen = set()

for x in arr:
    if x in seen:
        print("First repeating element is:", x)
        break
    seen.add(x)

First repeating element is: 3

In [12]:
arr = [10, 5, 3, 4, 3, 5, 6]

index_map = {}
min_index = len(arr)
result = None

for i, x in enumerate(arr):
    if x in index_map:
        if index_map[x] < min_index:
            min_index = index_map[x]
            result = x
    else:
        index_map[x] = i

print("First repeating element is:", result)

First repeating element is: 5

In [10]:
arr = [10, 5, 3, 4, 3, 5, 6, 10, 4, 6]

freq = {}

# Count frequency
for x in arr:
    freq[x] = freq.get(x, 0) + 1

# Find first non-repeating
for x in arr:
    if freq[x] == 1:
        print("First non-repeating element:", x)
        break
else:
    print("All elements are repeating")

All elements are repeating

#### stack balancing the brackets

In [11]:
def is_balanced(s):
    stack = []
    pairs = {')': '(', '}': '{', ']': '['}

    for ch in s:
        if ch in "({[":
            stack.append(ch)
        elif ch in ")}]":
            if not stack or stack[-1] != pairs[ch]:
                return False
            stack.pop()

    return len(stack) == 0


print(is_balanced("{[()]}"))  # True

True

In [4]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (2.3.3)

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Requirement already satisfied: numpy>=1.22.4 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pandas
Successfully installed pandas-2.3.3

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\hp\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1
  Using cached pytz-2026.1.post1-py2.py3-none-any.whl (510 kB)
Collecting numpy>=1.22.4
  Using cached numpy-2.2.6-cp310-cp310-win_amd64.whl (12.9 MB)
Collecting tzdata>=2022.7
  Using cached tzdata-2026.1-py2.py3-none-any.whl (348 kB)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Installing collected packages: pytz, tzdata, numpy, pandas
Successfully installed numpy-2.2.6 pandas-2.3.3 pytz-2026.1.post1 tzdata-2026.1

[notice] A new release of pip is available: 23.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd

data = {
    "id": [1, 2, 3, 4, 5, 6, 6],
    "name": ["Arjun", "Priya", "Rahul", "Sneha", "Amit", "Neha", "Neha"],
    "age": [25, 30, None, 22, 28, None, None],
    "salary": [50000, 60000, 55000, None, 65000, 70000, 70000],
    "department": ["IT", "HR", "IT", "Finance", None, "IT", "IT"]
}

df = pd.DataFrame(data)
print(df)

   id   name   age   salary department
0   1  Arjun  25.0  50000.0         IT
1   2  Priya  30.0  60000.0         HR
2   3  Rahul   NaN  55000.0         IT
3   4  Sneha  22.0      NaN    Finance
4   5   Amit  28.0  65000.0       None
5   6   Neha   NaN  70000.0         IT
6   6   Neha   NaN  70000.0         IT

In [6]:
df.head()

   id   name   age   salary department
0   1  Arjun  25.0  50000.0         IT
1   2  Priya  30.0  60000.0         HR
2   3  Rahul   NaN  55000.0         IT
3   4  Sneha  22.0      NaN    Finance
4   5   Amit  28.0  65000.0       None

In [8]:
df.shape

(7, 5)

In [9]:
df.columns

Index(['id', 'name', 'age', 'salary', 'department'], dtype='object')

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          7 non-null      int64
 1   name        7 non-null      object
 2   age         4 non-null      float64
 3   salary      6 non-null      float64
 4   department  6 non-null      object
dtypes: float64(2), int64(1), object(2)
memory usage: 408.0+ bytes

In [11]:
df.describe()

             id    age        salary
count  7.000000   4.00      6.000000
mean   3.857143  26.25  61666.666667
std    1.951800   3.50   8164.965809
min    1.000000  22.00  50000.000000
25%    2.500000  24.25  56250.000000
50%    4.000000  26.50  62500.000000
75%    5.500000  28.50  68750.000000
max    6.000000  30.00  70000.000000

In [12]:
df.isnull()

      id   name    age  salary  department
0  False  False  False   False       False
1  False  False  False   False       False
2  False  False   True   False       False
3  False  False  False    True       False
4  False  False  False   False        True
5  False  False   True   False       False
6  False  False   True   False       False

In [13]:
df.isnull().sum()

id            0
name          0
age           3
salary        1
department    1
dtype: int64

In [17]:
df.fillna(
    {
      "age": df['age'].mean(),
      "salary": df['salary'].mean() 
    }
)

   id   name    age        salary department
0   1  Arjun  25.00  50000.000000         IT
1   2  Priya  30.00  60000.000000         HR
2   3  Rahul  26.25  55000.000000         IT
3   4  Sneha  22.00  61666.666667    Finance
4   5   Amit  28.00  65000.000000       None
5   6   Neha  26.25  70000.000000         IT
6   6   Neha  26.25  70000.000000         IT

In [18]:
df["department"].fillna(df['department'].mode()[0])

0         IT
1         HR
2         IT
3    Finance
4         IT
5         IT
6         IT
Name: department, dtype: object

In [19]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [20]:
df.duplicated().sum()

np.int64(1)

In [21]:
df.drop_duplicates()

   id   name   age   salary department
0   1  Arjun  25.0  50000.0         IT
1   2  Priya  30.0  60000.0         HR
2   3  Rahul   NaN  55000.0         IT
3   4  Sneha  22.0      NaN    Finance
4   5   Amit  28.0  65000.0       None
5   6   Neha   NaN  70000.0         IT

In [26]:
df.loc[0:2]

   id   name   age   salary department
0   1  Arjun  25.0  50000.0         IT
1   2  Priya  30.0  60000.0         HR
2   3  Rahul   NaN  55000.0         IT

In [27]:
df.iloc[0:2]

   id   name   age   salary department
0   1  Arjun  25.0  50000.0         IT
1   2  Priya  30.0  60000.0         HR

In [29]:
df['encoded_salary'] = df['salary'].apply(lambda x: x/(df['salary'].mean()))
print(df)

   id   name   age   salary department  encoded_salary
0   1  Arjun  25.0  50000.0         IT        0.810811
1   2  Priya  30.0  60000.0         HR        0.972973
2   3  Rahul   NaN  55000.0         IT        0.891892
3   4  Sneha  22.0      NaN    Finance             NaN
4   5   Amit  28.0  65000.0       None        1.054054
5   6   Neha   NaN  70000.0         IT        1.135135
6   6   Neha   NaN  70000.0         IT        1.135135